### ISSUE TITLE
Strange fluctuations in weight

### ISSUE THREAD

**Issue by hammondses** [newAM/LoadCellOccupany#4]
Hi mate,

For some reason I'm getting some pretty huge random fluctuations in weight & can't really work out why, it seems to work pretty well (other than needing to calibrate it so it's actually accurate).

Have a look at the attached image, what does your homeassistant sensor graph look like?

![image](https://user-images.githubusercontent.com/21191206/47076946-6352e000-d25c-11e8-841d-b2364f527dcb.png)

**Comment by newAM** [comment]
That noise looks very impulsive, my initial guess is that it was a bad connection and shifting weight around is causing breaks, but you still get the noise without a load.  I have logging disabled for mine because it generates a ton of samples, but I am pretty sure I do not have impulses like that since my automation's would trigger when going from loaded to below 0kg.

My other guess would be power supply noise, has the original schematic been adapted?  If it has, was is your power source?

How wide are those impulses?  If they are just a sample or two this could be cleaned up with a median filter.

**Comment by hammondses** [comment]
Yeah i'm using a the esp8266 (somewhat) fork [Link](https://github.com/Skaronator/ESP8266-Load-Cell)

I'm using a 5v 2.1A power supply from my raspberry pi.

How would I tell how wide the impulses are? In the gui logging it shows no data for the sensor.

The points on the graph are always for only a 1 minute time frame, so I'm guessing its a sudden spike which is being recorded.

**Comment by newAM** [comment]
I'm using 3.3V, but I based the HX711 circuit on sparkfun's [HX711-Load-Cell-Amplifier](https://github.com/sparkfun/HX711-Load-Cell-Amplifier/), which says it's 5V tolerance so that should be OK.

Can you try a different power supply to see if it changes the noise?

If you know some basic C a median filter is not hard to implement, just take an array of the recent samples, and publish the median of those values.  If you can't do this yourself I can fork the repo you're working from and implement it there.

**Comment by hammondses** [comment]
I initially had it setup on my in wall 5v 2a USB port which also gave the same results, swapped to the RPI one figuring it's worth a shot, but no change unfortunately. 

I have zero C knowledge unfortunately, I was thinking I could also just do it in homeassistant with a filter, but implementing it at the source would definitely be better.

If you get a chance to have a go at it i'd be really grateful!

**Comment by newAM** [comment]
I pushed the code with filter here: https://github.com/newAM/ESP8266-Load-Cell

I did not have the libraries installed to compile it, so if it doesn't build let me know.
